### PR TITLE
fix: update metrics crate and remove unused import for rustc 1.94 compat

### LINKED ISSUE #435: v0.5.0 fails to build with rust-1.94.1
Hi,

Could you please cut a new release?

See, https://releng.netbsd.org/pkgreports/shadow/HEAD/NetBSD-11.0-x86_64/20260407.1802/inlyne-0.5.0/build.log

I get the same locally with Rust-1.95.0-beta7

```
error[E0521]: borrowed data escapes outside of associated function
   --> /usr/pkgsrc/textproc/inlyne/work/vendor/metrics-0.24.0/src/recorder/mod.rs:156:13
    |
146 | impl<'a> LocalRecorderGuard<'a> {
    |      -- lifetime `'a` defined here
147 |     /// Creates a new `LocalRecorderGuard` and sets the thread-local recorder.
148 |     fn new(recorder: &'a dyn Recorder) -> Self {
    |            -------- `recorder` is a reference that is only valid in the associated function body
...
156 |             LOCAL_RECORDER.with(|local_recorder| local_recorder.replace(Some(recorder_ptr)));
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |             |
    |             `recorder` escapes the associated function body here
    |             argument requires that `'a` must outlive `'static`
    |
note: raw pointer casts of trait objects cannot extend lifetimes
   --> /usr/pkgsrc/textproc/inlyne/work/vendor/metrics-0.24.0/src/recorder/mod.rs:153:60
    |
153 |         let recorder_ptr = unsafe { NonNull::new_unchecked(recorder as *const _ as *mut _) };
    |                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: this was previously accepted by the compiler but was changed recently
    = help: see <https://github.com/rust-lang/rust/issues/141402> for more information

For more information about this error, try `rustc --explain E0521`.
error: could not compile `metrics` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**EDIT:** The same error occurs while building from git-HEAD.

### PR DESCRIPTION
**Pull request by mrmodolo**
## Summary

This PR fixes a build failure with rustc 1.94+ and removes an unused import warning.

## Changes

- **Cargo.lock**: Bump `metrics` from 0.24.1 to 0.24.3 to fix `E0521` (borrowed data escapes outside of associated function) caused by a recent compiler change that rejects raw pointer casts extending lifetimes on trait objects. See https://github.com/rust-lang/rust/issues/141402
- **src/opts/cli.rs**: Remove unused `command` import from `clap` (flagged as warning)

## Reproduction

Building with `rustc 1.94.0` fails with:

error[E0521]: borrowed data escapes outside of associated function
 --> metrics-0.24.0/src/recorder/mod.rs:156:13

Fixed by running:
bash
cargo update -p metrics
cargo fix --bin "inlyne" -p inlyne --allow-dirty

### CODE REVIEW

**Review by CosmicHorrorDev — APPROVED** [review]
not sure why GitHub is pretending like there's no workflow checks to complete, but w/e. must just be another one of its ~~in~~frequent moments :shrug:
