### ISSUE TITLE
v0.5.0 fails to build with rust-1.94.1

### ISSUE THREAD

**Issue by 0323pin** [Inlyne-Project/inlyne#435]
Hi,

Could you please cut a new release?

See, https://releng.netbsd.org/pkgreports/shadow/HEAD/NetBSD-11.0-x86_64/20260407.1802/inlyne-0.5.0/build.log

I get the same locally with Rust-1.95.0-beta7

```
error[E0521]: borrowed data escapes outside of associated function
   --> /usr/pkgsrc/textproc/inlyne/work/vendor/metrics-0.24.0/src/recorder/mod.rs:156:13
    |
146 | impl<'a> LocalRecorderGuard<'a> {
    |      -- lifetime `'a` defined here
147 |     /// Creates a new `LocalRecorderGuard` and sets the thread-local recorder.
148 |     fn new(recorder: &'a dyn Recorder) -> Self {
    |            -------- `recorder` is a reference that is only valid in the associated function body
...
156 |             LOCAL_RECORDER.with(|local_recorder| local_recorder.replace(Some(recorder_ptr)));
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |             |
    |             `recorder` escapes the associated function body here
    |             argument requires that `'a` must outlive `'static`
    |
note: raw pointer casts of trait objects cannot extend lifetimes
   --> /usr/pkgsrc/textproc/inlyne/work/vendor/metrics-0.24.0/src/recorder/mod.rs:153:60
    |
153 |         let recorder_ptr = unsafe { NonNull::new_unchecked(recorder as *const _ as *mut _) };
    |                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: this was previously accepted by the compiler but was changed recently
    = help: see <https://github.com/rust-lang/rust/issues/141402> for more information

For more information about this error, try `rustc --explain E0521`.
error: could not compile `metrics` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**EDIT:** The same error occurs while building from git-HEAD.

**Comment by 0323pin** [comment]
Note that bumping `metrics` to release v0.24.3 should be enough to fix it.

**Comment by 0323pin** [comment]
That's already a PR for this, https://github.com/Inlyne-Project/inlyne/pull/429

**Comment by CosmicHorrorDev** [comment]
i can try handling things in a week or two. been very overwhelmed

**Comment by 0323pin** [comment]
No worries, @0-wiz-0 has patched `metrics` on NetBSD and the builds work again.
